services:
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build: 
      context: ./backend # Path to Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on: # Wait for the database to be ready
      - database

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_CONFIG_FILE=/var/lib/postgresql/data/postgresql.conf
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Initialize database
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf # Configuration
    ports:
      - "5432:5432"
    

volumes:
  db_data:

    
