FROM python:3.8-slim

# Set my working directory

WORKDIR /app

# Copy the current directory contents into the container at /app

COPY requirements.txt .

# Install python dependencies

RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app

COPY . .

# Expose the port the app runs on

EXPOSE 5000

# Run the application

CMD ["python", "app.py"]